server:
  port: 8083
spring:
  mail:
    host: smtp.qq.com
    username: 1475556814@qq.com
    password: fojg #开启POP3之后设置的客户端授权码
    default-encoding: UTF-8
  datasource:
    name: ex
    url: jdbc:mysql://127.0.0.1:3306/meet?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1
            # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
          # 连接池配
    druid:
      filters: stat,wall,slf4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #这里是mapper的配置文件
  type-aliases-package: com.crk.hs.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
